language: node_js

cache: npm

node_js:
  - 10.6.0

script:
  - npm run-script prod

deploy:
  provider: pages
  strategy: git
  local_dir: dist
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master