language: node_js

cache: npm

node_js:
  - 10.6.0

script:
  - npm run-script prod

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master